### ISSUE TITLE
Issue with 3.21_AnimationBlueprint in UE 5.1

### ISSUE THREAD

**Issue by kowalike** [PacktPublishing/Unreal-Engine-5---Endless-Runner#1]
I'm using Unreal Engine 5.1 and have encountered an issue with the 3.21_AnimationBlueprint character animations. After importing them, the animations play no problem when previewing, however when the game starts, the character runs for a second or two and then holds position. Any ideas why this might be?

**Comment by Sonakshis** [comment]
Hi,
It is possible that the speed variable is set to a higher value than 0 or the spawning is happening in midair, causing velocity to be produced.

**Comment by kowalike** [comment]
Where would I change the speed variable? The character keeps moving forward in the game, but the character does not continue the animation. It stops moving in the middle of the sequence and keeps going with arms frozen out.

**Comment by Sonakshis** [comment]
Hi, 
Regarding this query, please check to make sure the animation is set to "loop". It sounds like it may be stopping after playing once.

**Comment by kowalike** [comment]
Thanks, that worked. In the CharacterAnims_Run (state) under Details there is a Loop Animation checkbox that once checked resolved the issue!
